# -*- coding: utf-8 -*-
"""AIMLTask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6TLnfeNRrgXukLqFvKNn4QeoRSjQidG

Add `%load_ext cudf.pandas` before importing pandas to speed up operations using GPU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer

df = pd.read_csv('/content/Titanic-Dataset.csv')

print(df.info())
print(df.head())
print(df.describe())
print(df.isnull().sum())

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
cat_cols = df.select_dtypes(include=['object', 'category']).columns

num_imputer = SimpleImputer(strategy='median')
df[num_cols] = num_imputer.fit_transform(df[num_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols])

print(df.isnull().sum())

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

def remove_outliers_iqr(data, cols):
    for col in cols:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        data = data[(data[col] >= lower_bound) & (data[col] <= upper_bound)]
    return data

df_clean = remove_outliers_iqr(df, num_cols)

print(f"Original data shape: {df.shape}")
print(f"Data shape after outlier removal: {df_clean.shape}")